### PR TITLE
Upgrade broccoli-caching-writer

### LINKED ISSUE #3: Update broccoli-plugin
This addon is using an older version of broccoli-plugin which is incompatible with newer ember-cli versions. Would a pull-request be desired?

### PR DESCRIPTION
**Pull request by rmachielse**
Fixes #3 

This pr rewrites the broccoli plugin to be compatible with the new plugin structure

### CODE REVIEW

**Comment by rmachielse** [comment]
@MojoJojo can you have a look at this?

**Comment by MojoJojo** [comment]
Hey..sorry for the delayed response. Was traveling..just got back to day. Will have a look.

**Comment by rmachielse** [comment]
Awesome! No worries

**Comment by rmachielse** [comment]
Hi @MojoJojo! Have some time to look into this soon?

**Comment by MojoJojo** [comment]
Merged!

**Comment by rmachielse** [comment]
Awesome, thanks! Feel like a release soon?

**Comment by rmachielse** [comment]
@MojoJojo any chances on a release?

**Comment by MojoJojo** [comment]
Just released! Sorry for the delay, been quite busy this side!

**Comment by rmachielse** [comment]
Fantastic, thanks!

**Pull request merged**
