### PR TITLE
Upgrade less

### PR DESCRIPTION
**Pull request by rmachielse**
This pr upgrades less to the next major release

### CODE REVIEW

**Comment by rmachielse** [comment]
@MojoJojo we have tested this on our codebase and the upgrade is working fine. Any chance on a quick merge and release?

**Comment by MojoJojo** [comment]
Hi @rmachielse ,
Thanks for the PR! Much appreciated. I will review and merge it before I finish work today.

**Comment by rmachielse** [comment]
Thanks for the quick merge @MojoJojo! A release will be appreciated 😄

**Comment by MojoJojo** [comment]
Published. Can you please confirm if upgrading to `1.0.6` works for you?

**Comment by rmachielse** [comment]
@MojoJojo it's working like a charm, thank you for the quick turnaround!

**Pull request merged**
