### PR TITLE
Upgrade node-sass

### PR DESCRIPTION
**Pull request by rmachielse**
This pr upgrades node-sass to the next major release

### CODE REVIEW

**Comment by rmachielse** [comment]
@MojoJojo we have tested this on our setup and it doesn't seem to cause any problems. Why does this package need `node-sass` anyway?

**Comment by MojoJojo** [comment]
@rmachielse First of all, a big thank you for the PR! 
I will merge the PR shortly. The project needs a little clean up and some tidying up (including the sass dependency you mentioned)...I will clean it up today and publish the new version.

Thank you once again for the PR!

**Comment by rmachielse** [comment]
@MojoJojo great, thanks a lot for that!

**Comment by rmachielse** [comment]
@MojoJojo any updates on this? Do you intend to release a new version soon?

**Comment by MojoJojo** [comment]
Hi @rmachielse apologies ...got a bit too busy with another project. I will attend to it this weekend.

**Comment by MojoJojo** [comment]
@rmachielse Quick question - are you using this plugin with Ember CLI?

**Comment by rmachielse** [comment]
@MojoJojo yes I am

**Comment by MojoJojo** [comment]
Just released the new package on NPM. Thinking of re-writing and publishing this as an ember cli plugin instead..

**Comment by rmachielse** [comment]
@MojoJojo thanks for that! That would be even more convenient, although we're already happy with the addon the way it is

**Pull request merged**
